/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import hms.models.doctor;
import java.awt.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Student
 */
public class doctordetails extends javax.swing.JFrame {

    /**
     * Creates new form doctordetails
     */
    public doctordetails() {
        try {
            initComponents();
            DatabaseConnection.displayDoctorTable(dtable);
        } catch (SQLException ex) {
            Logger.getLogger(doctordetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dgender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ddept = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        dcnic = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        duser = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dpass = new javax.swing.JPasswordField();
        Delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 149, 96));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor Details");

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Doctor ID");

        did.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" Name:");

        dname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dnameKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Age: ");

        dage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Gender: ");

        dgender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Department: ");

        ddept.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ddept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "General", "Dentist", "Skin Specialist", "Eye Specialist", "Heart Specialist", "ENT" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("CNIC: ");

        dcnic.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 255));
        jButton4.setText("Add Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Username: ");

        duser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Password: ");

        dpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        Delete.setBackground(new java.awt.Color(255, 255, 204));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(51, 0, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 0, 255));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "CNIC", "Gender", "Age", "Password", "Department"
            }
        ));
        dtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(34, 34, 34)
                                .addComponent(duser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(dpass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(did, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(dname))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dgender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dcnic, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(10, 10, 10)
                                        .addComponent(ddept, 0, 160, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(dgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Delete)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dcnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel18)
                    .addComponent(duser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(dpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminpanel ap = new adminpanel();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String di = did.getText();
        String dn = dname.getText();
        String da = dage.getText();
        String dg = dgender.getSelectedItem().toString();
        String du = duser.getText();
        String dc = dcnic.getText();
        String dp = dpass.getText();
        String dd = ddept.getSelectedItem().toString();

        if (di.length() > 0 && dn.length() > 0 && da.length() > 0 && dgender.getSelectedIndex() != 0 && du.length() > 0 && dc.length() > 0 && dp.length() > 0 && ddept.getSelectedIndex() != 0) {
            if (di.matches("^[0-9]*$") && da.matches("^[0-9]*$") && dc.matches("^[0-9]*$") && dc.length() == 13) {
                try {
//                    DefaultTableModel doctor = (DefaultTableModel) dtable.getModel();
//                    doctor.addRow(new Object[]{
//                        di, dn, du, dc, dg, da, dp, dd
//                    });
                    DatabaseConnection.insertIntoDoctorTable(di, dn,du, dc, dg, da, dp, dd) ;
                    DatabaseConnection.displayDoctorTable(dtable);
                    JOptionPane.showMessageDialog(rootPane, "Doctor Added Successfully");
                    did.setText(null);
                    dname.setText(null);
                    dage.setText(null);
                    duser.setText(null);
                    dcnic.setText(null);
                    dpass.setText(null);
                    dgender.setSelectedIndex(0);
                    ddept.setSelectedIndex(0);
                } catch (SQLException ex) {
                    Logger.getLogger(doctordetails.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "ID, Age & CNIC must be a number \n CNIC must be 13 digits");
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "Enter All Entries");
        }
//        char[] pass = dpass.getPassword();
//        String namei=dname.getText();
//        String age;
//        age = dage.getText();
//        String ID =  did.getText();
//        String CNIC =  dcnic.getText();
//        if(ID.length()==4 && ID.matches("^[0-9]*$"))
//        {
//            if(age.matches("^[0-9]*$"))
//            {
//                 if(CNIC.length()==13 && CNIC.matches("^[0-9]*$"))
//                 {
//                     if(pass.length>=8)
//                     {
//                         if(age.length()>0 && duser.getText().length()>0 && dname.getText().length()>0)
//                         {
//                            doctordetails d = new doctordetails();
//                            d.setVisible(true);
//                            this.dispose();    
//                         }
//                         else
//                         {
//                             JOptionPane.showMessageDialog(rootPane, "Enter all Enteries");
//    
//                         }
//    
//                     }
//                     else
//                     {
//                        JOptionPane.showMessageDialog(rootPane, "Enter 8 digit password");
//                     }
//                 }
//                 else
//                 {
//                    JOptionPane.showMessageDialog(rootPane,"CNIC Not Valid");
//     
//                 }
//  
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(rootPane,"Age Not Valid");    
//            }
//        }
//        
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane,"ID Not Valid\nMust be 4 digit\nOnly digits Allowed");
//        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void dnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c)) {
            dname.setEditable(true);
        } else {
            dname.setEditable(false);
        }
    }//GEN-LAST:event_dnameKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        did.setText(null);
        dname.setText(null);
        dage.setText(null);
        duser.setText(null);
        dcnic.setText(null);
        dpass.setText(null);
        dgender.setSelectedIndex(0);
        ddept.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            // TODO add your handling code here:
            DatabaseConnection.deleteDoctorTableRow(dtable);
            DefaultTableModel doctor = (DefaultTableModel) dtable.getModel();
            if (dtable.getSelectedRow() >= 0) {
                doctor.removeRow(dtable.getSelectedRow());
                JOptionPane.showMessageDialog(rootPane, "Doctor deleted successfully");
                did.setText(null);
                dname.setText(null);
                dage.setText(null);
                duser.setText(null);
                dcnic.setText(null);
                dpass.setText(null);
                dgender.setSelectedIndex(0);
                ddept.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Select the row first");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doctordetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void dtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel doctor = (DefaultTableModel) dtable.getModel();
        String paid = doctor.getValueAt(dtable.getSelectedRow(), 0).toString();
        String pan = doctor.getValueAt(dtable.getSelectedRow(), 1).toString();
        String pad = doctor.getValueAt(dtable.getSelectedRow(), 2).toString();
        String pac = doctor.getValueAt(dtable.getSelectedRow(), 3).toString();
        String pag = doctor.getValueAt(dtable.getSelectedRow(), 4).toString();
        String paa = doctor.getValueAt(dtable.getSelectedRow(), 5).toString();
        String pab = doctor.getValueAt(dtable.getSelectedRow(), 6).toString();
        String pat = doctor.getValueAt(dtable.getSelectedRow(), 7).toString();
        did.setText(paid);
        dname.setText(pan);
        dage.setText(paa);
        duser.setText(pad);
        dcnic.setText(pac);
        dpass.setText(pab);
        dgender.setSelectedItem(pag);
        ddept.setSelectedItem(pat);
        
        // to disable the text field of id when a row is selected
             did.setEnabled(false);
    }//GEN-LAST:event_dtableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        // TODO add your handling code here:
        String id = did.getText();
        String name = dname.getText();
        String age = dage.getText();
        String gender = dgender.getSelectedItem().toString();
        String user = duser.getText();
        String cnic = dcnic.getText();
        String dept = ddept.getSelectedItem().toString();
        String pass = dpass.getText();
        if (dtable.getSelectedRow() >= 0) {
            if (name.length() > 0 && dgender.getSelectedIndex() != 0 && ddept.getSelectedIndex() != 0 && user.length() > 0) {
                if (cnic.matches("^[0-9]*$") && age.matches("^[0-9]*$") && id.matches("^[0-9]*$") && cnic.length() == 13) {

                    try {
                        DefaultTableModel model = (DefaultTableModel) dtable.getModel();
                        model.setValueAt(did.getText(), dtable.getSelectedRow(), 0);
                        
                        model.setValueAt(dname.getText(), dtable.getSelectedRow(), 1);
                        model.setValueAt(duser.getText(), dtable.getSelectedRow(), 2);
                        model.setValueAt(dcnic.getText(), dtable.getSelectedRow(), 3);
                        model.setValueAt(dgender.getSelectedItem(), dtable.getSelectedRow(), 4);
                        model.setValueAt(dage.getText(), dtable.getSelectedRow(), 5);
                        model.setValueAt(dpass.getText(), dtable.getSelectedRow(), 6);
                        model.setValueAt(ddept.getSelectedItem(), dtable.getSelectedRow(), 7);
                        DatabaseConnection.updateDoctorTableRow(dtable);
                        JOptionPane.showMessageDialog(rootPane, "Doctor Updated Successfully");
                        did.setText(null);
                        dname.setText(null);
                        dage.setText(null);
                        duser.setText(null);
                        dcnic.setText(null);
                        dpass.setText(null);
                        dgender.setSelectedIndex(0);
                        ddept.setSelectedIndex(0);
                    } catch (SQLException ex) {
                        Logger.getLogger(doctordetails.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "ID, CNIC & Age must be a number \n CNIC must be 13 digits");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter All Entries");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, " Select the row first");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctordetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTextField dage;
    private javax.swing.JTextField dcnic;
    private javax.swing.JComboBox<String> ddept;
    private javax.swing.JComboBox<String> dgender;
    private javax.swing.JTextField did;
    private javax.swing.JTextField dname;
    private javax.swing.JPasswordField dpass;
    private javax.swing.JTable dtable;
    private javax.swing.JTextField duser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
