/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class employeesdetails extends javax.swing.JFrame {

    /**
     * Creates new form employeesdetails
     */
    public employeesdetails() throws SQLException {
        initComponents();
        DatabaseConnection d = new DatabaseConnection();

        //for display of select query in jtable
        DatabaseConnection.displayEmployeeTable(stable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        scnic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sgender = new javax.swing.JComboBox<>();
        stype = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 149, 96));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lower Staff Details");

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Staff ID ");

        sid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Name: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("CNIC: ");

        sname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        scnic.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Age: ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Gender: ");

        sage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Staff Type: ");

        sgender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));

        stype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Nurse", "Therapist", "Medical Assistant", "Pharmacist", "Accountant", "Food Service", "Volunteers", "Ward Clerks" }));
        stype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stypeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setText("Add Employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Delete Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 255));
        jButton4.setText("Update Employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "CNIC", "Gender", "Age", "Staff Type"
            }
        ));
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sname)
                            .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addComponent(scnic, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sgender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(stype, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(stype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(sage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(sgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(scnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminpanel ap = new adminpanel();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        employeesdetails ed = new employeesdetails();
//        if (sid.getText().length()>0 && sname.getText().length()>0 && scnic.getText().length()>0 && stype.getSelectedIndex()!=0 && sage.getText().length()>0 && sgender.getSelectedIndex()!=0){
//            if (sid.getText().matches("^[0-9]*$") && sid.getText().length()==4){
//                if (sage.getText().matches("^[0-9]*$")){
//                    JOptionPane.showMessageDialog(rootPane, "employee added successfully");
//                    ed.setVisible(true);
//                }
//                else {JOptionPane.showMessageDialog(rootPane, "Enter Valid age");}
//            }
//            else {JOptionPane.showMessageDialog(rootPane, "Enter 4 digit ID");}
//        }
//        else{JOptionPane.showMessageDialog(rootPane, "Enter All entries");}
        String staff_id = sid.getText();
        String name = sname.getText();
        String age = sage.getText();
        String gender = sgender.getSelectedItem().toString();
        String cnic = scnic.getText();
        String staff_type = stype.getSelectedItem().toString();

        if (staff_id.length() > 0 && name.length() > 0 && age.length() > 0 && sgender.getSelectedIndex() != 0 && cnic.length() > 0 && stype.getSelectedIndex() != 0) {
            if (staff_id.matches("^[0-9]*$") && age.matches("^[0-9]*$") && cnic.matches("^[0-9]*$") && cnic.length() == 13) {
                try {
                    //                DefaultTableModel employe = (DefaultTableModel) stable.getModel();
//                employe.addRow(new Object[]{
//                    staff_id, name,cnic,gender, age, staff_type
//                });
//insert query
                    try {
                        DatabaseConnection.insertData(staff_id, name, cnic, gender, age, staff_type);
                    } catch (SQLException ex) {
                        Logger.getLogger(employeesdetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    DatabaseConnection.displayEmployeeTable(stable);
                    JOptionPane.showMessageDialog(rootPane, "Patient Added Successfully");
                    sid.setText(null);
                    sname.setText(null);
                    sage.setText(null);
                    scnic.setText(null);
                    sgender.setSelectedIndex(0);
                    stype.setSelectedIndex(0);
                } catch (SQLException ex) {
                    Logger.getLogger(employeesdetails.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "ID, Age & CNIC must be a number \n CNIC must be 13 digits");
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "Enter All Entries");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            DatabaseConnection.deleteSelectedRow(stable);

            DefaultTableModel employe = (DefaultTableModel) stable.getModel();
            if (stable.getSelectedRow() >= 0) {
                employe.removeRow(stable.getSelectedRow());
                JOptionPane.showMessageDialog(rootPane, "Patient deleted successfully");
                sid.setText(null);
                sname.setText(null);
                sage.setText(null);
                scnic.setText(null);
                sgender.setSelectedIndex(0);
                stype.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Select the row first");
            }

//        employeesdetails ed = new employeesdetails();
//        JOptionPane.showMessageDialog(rootPane, "Employee Deleted succeessfully");
//        ed.setVisible(true);
//        this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(employeesdetails.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = sid.getText();
        String name = sname.getText();
        String age = sage.getText();
        String gender = sgender.getSelectedItem().toString();
        String cnic = scnic.getText();
        String type = stype.getSelectedItem().toString();
        if (stable.getSelectedRow() >= 0) {
            if (name.length() > 0 && sgender.getSelectedIndex() != 0 && stype.getSelectedIndex() != 0) {
                if (cnic.matches("^[0-9]*$") && age.matches("^[0-9]*$") && id.matches("^[0-9]*$")) {

                    try {
                        DefaultTableModel model = (DefaultTableModel) stable.getModel();
                        model.setValueAt(sid.getText(), stable.getSelectedRow(), 0);
                        model.setValueAt(sname.getText(), stable.getSelectedRow(), 1);
                        model.setValueAt(scnic.getText(), stable.getSelectedRow(), 2);
                        model.setValueAt(sgender.getSelectedItem(), stable.getSelectedRow(), 3);
                        model.setValueAt(sage.getText(), stable.getSelectedRow(), 4);
                        model.setValueAt(stype.getSelectedItem(), stable.getSelectedRow(), 5);

                        //update table
                        DatabaseConnection.updateEmployeeTable(stable);
                        JOptionPane.showMessageDialog(rootPane, "Receptionist Updated Successfully");
                        sid.setText(null);
                        sname.setText(null);
                        sage.setText(null);
                        scnic.setText(null);
                        sgender.setSelectedIndex(0);
                        stype.setSelectedIndex(0);
                    } catch (SQLException ex) {
                        Logger.getLogger(employeesdetails.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bed # & Room# must be a number");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter All Entries");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, " Select the row first");
        }

//        employeesdetails ed = new employeesdetails();
//        if (sid.getText().length()>0 && sname.getText().length()>0 && scnic.getText().length()>0 && stype.getSelectedIndex()!=0 && sage.getText().length()>0 && sgender.getSelectedIndex()!=0){
//            if (sid.getText().matches("^[0-9]*$") && sid.getText().length()==4){
//                if (sage.getText().matches("^[0-9]*$") ){
//                    JOptionPane.showMessageDialog(rootPane, "employee added successfully");
//                    ed.setVisible(true);
//                }
//                else {JOptionPane.showMessageDialog(rootPane, "Enter Valid age");}
//            }
//            else {JOptionPane.showMessageDialog(rootPane, "Enter 4 digit ID");}
//        }
//        else{JOptionPane.showMessageDialog(rootPane, "Enter All entries");}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void stypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stypeActionPerformed

    private void stableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel employe = (DefaultTableModel) stable.getModel();
        String paid = employe.getValueAt(stable.getSelectedRow(), 0).toString();
        String pan = employe.getValueAt(stable.getSelectedRow(), 1).toString();
        String pac = employe.getValueAt(stable.getSelectedRow(), 2).toString();
        String pag = employe.getValueAt(stable.getSelectedRow(), 3).toString();
        String paa = employe.getValueAt(stable.getSelectedRow(), 4).toString();
        String pat = employe.getValueAt(stable.getSelectedRow(), 5).toString();
        sid.setText(paid);
        sname.setText(pan);
        sage.setText(paa);
        scnic.setText(pac);
        sgender.setSelectedItem(pag);
        stype.setSelectedItem(pat);

        // to disable the text field of id when a row is selected
        sid.setEnabled(false);
    }//GEN-LAST:event_stableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeesdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeesdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeesdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeesdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new employeesdetails().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(employeesdetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sage;
    private javax.swing.JTextField scnic;
    private javax.swing.JComboBox<String> sgender;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTable stable;
    private javax.swing.JComboBox<String> stype;
    // End of variables declaration//GEN-END:variables
}
